### Álgebra Linear com Python

Escalares = tipos: int, float, str

Biblioteca utilizada: Numpy

Ex.:

importando a biblioteca numpy

In [1]:
import numpy as np

In [2]:
var1 = 7
var2 = 5.3
var3 = 'python'

print(var1, var2, var3)

7 5.3 python


Vetores - São arrays, isto é, conjunto de escalares

Ex.:

In [3]:
array = np.array([var1, var2, var3])

In [4]:
array

array(['7', '5.3', 'python'], dtype='<U32')

Matriz - São conjuntos de vetores

Exemplo de uma matriz 3 x 3 - conjunto de 3 vetores com 3 escalares.

In [7]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Matriz diagonal e triângular

Matriz quadrada é quando o número de linhas e colunas são iguais como no exemplo acima, uma matriz 
com 3 colunas e 3 linhas, e quando ela é quadrada DIAGONAL é quando todos os números fora da diagonal 
são nulos ou iguais a zero.

Ex.:

In [8]:
diagonal = np.diag([1, 2, 3])
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Matriz triângular SUPERIOR, é quando os números ACIMA da diagonal principal, são iguais a zero e triângular
INFERIOR, quando os números ABAIXO da diagonal principal são iguais a zero.

Ex.:

In [12]:
SUPERIOR = np.array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
SUPERIOR

array([[1, 0, 0],
       [2, 3, 0],
       [4, 5, 6]])

In [14]:
INFERIOR = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
INFERIOR

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 6]])

Matriz linha ou coluna

In [15]:
mat_linha = np.transpose([[1, 2, 3, 4]])
mat_linha

array([[1],
       [2],
       [3],
       [4]])

ou

In [16]:
mat_col = np.array([[1], [2], [3], [4]])
mat_col

array([[1],
       [2],
       [3],
       [4]])

Matriz Nula = quando todos os seus elementos são iguais a zero

Ex.:

In [18]:
mat_nula = np.zeros([3, 3])
mat_nula

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Matriz Identidade = quando todos os elementos de sua diagonal principal são iguais a 1.

Ex.:

In [22]:
indent = np.eye(3, 3)
indent

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ou

In [24]:
indent = np.identity(3)
indent

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])